DELIMITER $$
CREATE TRIGGER prevent_insert

BEFORE INSERT
ON emp FOR EACH ROW
BEGIN
		IF( CURRENT_TIME() BETWEEN '17:00' AND '00:00') THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES';
		END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER prevent_update

BEFORE UPDATE
ON emp FOR EACH ROW
BEGIN
		IF( CURRENT_TIME() BETWEEN '17:00' AND '00:00') THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES';
		END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER prevent_delete

BEFORE DELETE
ON emp FOR EACH ROW
BEGIN
		IF( CURRENT_TIME() BETWEEN '17:00' AND '00:00') THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES';
		END IF;
END $$
DELIMITER ;

